### ISSUE TITLE
path setting does not work on windows

### ISSUE THREAD

**Issue by xinstein** [ManuelHentschel/VSCode-R-Debugger#124]
**NOTE:** Before submitting an issue, please make sure to install the latest version of both the vscode extension and the R package. This can usually be achieved by running the command `r.debugger.updateRPackage` in vscode's command palette (`F1`).

**Describe the bug**
on windows we need the extra & sign in front of the executable path in order to launch R, which is handled properly by the R extension bu not by r-debugger extension.
Previously there's the separate rdebugger.rpath setting which could be set to `& "z:\path\to\R.exe"` to overcome this issue, but from some version on this setting is deprecated.

**To Reproduce**
1. set rpath to `z:\path\to\R.exe`
2. launch anything from this extension (could be "install or update packages" or launch an r debugging task)

**Comment by ManuelHentschel** [comment]
I'm using windows as well and I'm not having these issues.
Just to be sure, since there have been some changes recently, are you using `"r.rpath.windows"`? This is a different setting from `"r.rterm.windows"` which is used by vscode-R for most things.

If you installed R using the default settings, you could also try leaving the setting blank, and let the extension read the R path from the registry.

**Comment by gwd999** [comment]
I am also exhibiting various issues on WINDOWS 10 PRO 20H2 
```
"rStrings": {
    "prompt": "<#v\\s\\c>",
    "continue": "<##v\\s\\c>",
    "startup": "<v\\s\\c\\R\\STARTUP>",
    "libraryNotFound": "<v\\s\\c\\LIBRARY\\NOT\\FOUND>",
    "packageName": "vscDebugger"
  },   
```
does not feel right? Should the "libraryNotFound" make me worry? 
None of the  Debug Configurations (File, Function) start up. 
I do have a custom R package library .libPath set in Rprofile.site pointig to another partition "D:\"  
I also tried installing "vscDebugger" in the default R_HOME\library - which did not fix the issue. 
Debug Config "Attach to R process" throws: 

![image](https://user-images.githubusercontent.com/306826/111077225-0b356c00-84f0-11eb-9b37-8508efe799de.png)

**Comment by ManuelHentschel** [comment]
>  Should the "libraryNotFound" worry me?

Not at all, those strings are just internal information (for debugging the debug extension itself). I should probably remove these, since they can be a bit misleading.


*"Launch R-Workspace"* is the most basic of the default debug configs, so I'd recommend trying to get that one to work first. What's the behavior if you try launching the debugger with this config?

**Comment by ManuelHentschel** [comment]
@xinstein Any updates on this issue? If not I'd close this as stale, since we could work out @gwd999 's problems in a separate issue.

**Comment by xinstein** [comment]
Sorry, I forgot to make update to this thread. It's okay to close it, I eventually resolved it by unsetting rpath in vscode and setting environment variable prior to launching vscode
