### ISSUE TITLE
source uses wrong environment during debugging

### ISSUE THREAD

**Issue by bersbersbers** [ManuelHentschel/VSCode-R-Debugger#136]
**Describe the bug**
Parameter `b` is not passed to the `source`d `b.R` when the `source` command is in a function.

Remove `rm(b)` to see that `b.R` sees `b == 1` incorrectly.

**To Reproduce**
Debug the code below.

**Your R code**
```R
file_conn <- file("b.R")
writeLines("message(b)", file_conn)
close(file_conn)

# this works
b <- 1
source("b.R")
rm(b)

# this fails
call_b <- function() {
    b <- 2
    source("b.R")
}
call_b()
```

**Your Launch config**
If applicable, the launch config that causes the bug. E.g.:
``` json
{
    "name": "R: Current File",
    "presentation": {
        "group": "00 User",
        "order": 20,
    },
    "type": "R-Debugger",
    "request": "launch",
    "file": "${fileDirname}/${fileBasenameNoExtension}.R",
    "debugMode": "file",
    "allowGlobalDebugging": true,
    "workingDirectory": "${fileWorkspaceFolder}",
}
```

**Expected behavior**
```
1
2
```

**Actual behavior**
```
1
Error in message(b) : object 'b' not found
```

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 remoting into Linux
 - R Version: 4.0.4
 - vscDebugger Version: 0.4.6
 - vscode-r-debugger Version: rdebugger.r-debugger v0.4.6

**Comment by bersbersbers** [comment]
(I was quite sure I tested that this works in `Rscript`, but it seems it does not, either. Investigating if this can be closed immediately.)

**Comment by ManuelHentschel** [comment]
Glad you could figure this out. Quick side note on `source()`: This function is by default overwritten by `.vsc.debugSource()`, which does (mostly) the same thing, but respects breakpoints. I tried writing this function so that it can be used just like `source()`, but some arguments that work with `base::source` are simply ignored by `.vsc.debugSource`. The `local` argument should work as expected, some other arguments might not work properly, though.
