### ISSUE TITLE
Add svSocket to install.R

### ISSUE THREAD

**Issue by bersbersbers** [ManuelHentschel/VSCode-R-Debugger#140]
I just received this upon `r.debugger.updateRPackage` in WSL (Ubuntu 20.04) with R 3.6.3:
```
> url <- commandArgs(trailingOnly = TRUE)[[1]]
> install.packages(url, repos = NULL)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://github.com/ManuelHentschel/VSCode-R-Debugger/releases/download/v0.4.6/vscDebugger_0.4.6.tar.gz'
Content type 'application/octet-stream' length 331497 bytes (323 KB)
==================================================
downloaded 323 KB

ERROR: dependency ‘svSocket’ is not available for package ‘vscDebugger’
* removing ‘/usr/local/lib/R/site-library/vscDebugger’
Warning message:
In install.packages(url, repos = NULL) :
  installation of package ‘/tmp/RtmpNR4bSY/downloaded_packages/vscDebugger_0.4.6.tar.gz’ had non-zero exit status
>
```

`install.packages("svSocket")` fixed this - would it make sense to add that to `install.R` as well?

**Comment by ManuelHentschel** [comment]
See https://github.com/ManuelHentschel/vscDebugger/pull/157 and https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/130.

I'm still not really sure how to handle this, since the part of the debugger that uses svSocket is a somewhat experimental feature and depends on a custom fork of svSocket.

**Comment by tdeenes** [comment]
I think I will have time on the weekend to do some experiments with this.

**Comment by bersbersbers** [comment]
`svSocket` 1.0.2 was released yesterday, if that makes a difference for this issue.

**Comment by ManuelHentschel** [comment]
Since the svSocket maintainers haven't responded to my question, I assume that they are not planning to implement the changes required to use svSocket here, so I'll just remove svSocket from the imports for now. Hopefully I'll get around to implementing a clean socket solution inside vscDebugger at some point.
