### ISSUE TITLE
Packages cannot be loaded when renv is installed in subfolder of workspaceFolder

### ISSUE THREAD

**Issue by marecabo** [ManuelHentschel/VSCode-R-Debugger#149]
**Describe the bug**
Debugging an R file, while using an renv that has been created in a *subfolder* of `${workspaceFolder}`, despite configuring `"workingDirectory": "${workspaceFolder}\\subfolder"` in the launch config, cannot load packages with `library()` commands in the debugged file. When creating the exact same renv in the `${workspaceFolder}`, loading of packages works as expected

**To Reproduce** / **Your R code**
Please see the minimum working and not-working example and the readme here: https://github.com/marecabo/ManuelHentschel-VSCode-R-Debugger-149

**Your Launch config**
``` json
        {
            "type": "R-Debugger",
            "name": "Debug R-File",
            "request": "launch",
            "debugMode": "file",
            "workingDirectory": "${workspaceFolder}\\another-folder",
            "file": "${file}"
        },
```

**Expected behavior**
I expect installed packages to be loaded while debugging an R-file, regardless where the renv is installed as long as the `workingDirectory` property of the launch config points to the folder containing the `.Rprofile` of the desired renv.

**Actual behavior**
In the debugged file, packages installed in the renv cannot be loaded.

```log
Error in library("tidytransit") : 
  there is no package called 'tidytransit'
```

**Desktop:**
 - OS: Windows 10 1909 18363.1734 x64 
 - R Version: 4.1.1 x64
 - vscDebugger Version: 0.4.7
 - vscode-r-debugger Version: 0.4.7

**Additional Context:**
Thank you for your work at this extension.

**Comment by ManuelHentschel** [comment]
Thanks for raising this very well documented issue! I could reproduce the behavior, and unfortunately that's also the expected behavior at the moment.

The problem is caused by the fact that the launch configuration is handled inside R. So, when starting the R process, the VSCode-R-Debugger extension does not consider the `workingdirectory`, instead the R-package vscDebugger uses `setwd()` during the launch sequence to change to that directory.

As a temporary workaround, you can either set up renv in the workspace folder, or launch vscode in the subfolder when debugging.

I think the cleanest way to fix this would be to implement a `launchDirectory` in the launch config that is used by the vscode extension to launch R in the correct folder. This should probably default to the `workingDirectory` to avoid confusion.
