### ISSUE TITLE
Breakpoints not working

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#26]
With latest commit of vscDebugger and VSCode-R-Debugger, breakpoints do not work any more as I launch the extension on either `testMain.R` or `test.R`. Not sure if I miss something?

Just see the following as I press Run or Continue:

<img width="716" alt="image" src="https://user-images.githubusercontent.com/4662568/83365208-26a80e00-a3d9-11ea-853b-d1d02ace90a5.png">

**Comment by ManuelHentschel** [comment]
I made some changes to the launch process and launch config and apparently didn’t clean up the test folder. 

The „sourcing stuff“ is actually printed at the beginning of testMain.R, but main() is never called, because of the new launch configuration. 

I hope it works, if you set debugFunction to true in the launch config or just call main() from the debug console. 

If not, please let me know, sorry about the mess!

**Comment by renkun-ken** [comment]
Thanks! I set `debugFunction` to true and `mainFunction` to `main` and it works now.
