### ISSUE TITLE
The meaning of allowGlobalDebugging

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/VSCode-R-Debugger#37]
I don't quite understand the meaning of `allowGlobalDebugging` in `launch.json`, as the latest commit uses `allowGlobalDebugging = false` in `R Debug Function` launch item and launching any of the test R scripts does not hit any breakpoint and `browser()` call. Am I missing something?

Explicit calling `main()` in the end of `objects.R` will make launch hit `browser()` but not any breakpoints.

**Comment by ManuelHentschel** [comment]
In https://github.com/ManuelHentschel/VSCode-R-Debugger/pull/38 I made some changes to the debug config.

The (intended) effect of `allowGlobalDebugging` did not change, but it was not working properly before.

If `allowGlobalDebugging = false` the debugger is supposed to run the specified file or function and then exit. This is particularly useful when debugging a single `main()` function, since usually there are no interesting variables in the global workspace afterwards anyways.

If `allowGlobalDebugging = true` the debugger keeps running after executing a function or file and allows interactive use of the debug console, similar to a regular terminal window.


Especially the case `allowGlobalDebugging = false` was somewhat hard to get working properly, since the communication between vscode and R is very async due to the somewhat unpredictable behaviour of `stdio`, which made it hard to differentiate if e.g. a prompt was shown before or after running `main()`. In my test cases it works as expected now, but let me know if you have any problems or I missed any combinations of `debugMode`, breakpoints, and console input.

**Comment by renkun-ken** [comment]
Thanks for the detailed explanation!

I'm trying the latest commit of vscDebugger and VSCode-R-Debugger by launching at `objects.R`, but the following error occurs:

```
Starting R session...
rDelimiter0: <v\s\c>
rDelimiter1: </v\s\c>
rPrompt: <#v\s\c>
rContinue: <##v\s\c>
rStartup: <v\s\c\R\STARTUP>
rLibraryNotFound: <v\s\c\LIBRARY\NOT\FOUND>
rAppend:  ### <v\s\c\COMMAND>
cwd: /Users/ken/Workspaces/github/VSCode-R-Debugger/test/R
rPath: /usr/local/bin/R
rArgs: --ess --quiet --interactive --no-save
library: vscDebugger
overwrite print(): true
overwrite cat(): true
overwrite source(): true
allow global debugging: false
set breakpoints in packages: false
program: /Users/ken/Workspaces/github/VSCode-R-Debugger/test/R/objects.R
main function: main()
Error in vscDebugger::.vsc.prepGlobalEnv(overwritePrint = TRUE, overwriteCat = TRUE,  : 
  unused argument (debugGlobal = FALSE)
```

Looks like there's typo somewhere?

**Comment by ManuelHentschel** [comment]
Are you sure you're on the latest version? The argument `debugGlobal` should not be used by the debugger anymore: https://github.com/ManuelHentschel/VSCode-R-Debugger/blob/develop/src/debugRuntime.ts#L216

And using `ctrl+shift+f` I can't even find the word anywhere in my code...

**Comment by renkun-ken** [comment]
Sorry, my mistake, just found my git pull does not succeed. I redo git pull and everything looks good now.
