### ISSUE TITLE
R path not working

### ISSUE THREAD

**Issue by FelixBenning** [ManuelHentschel/VSCode-R-Debugger#76]
### Error message

```
R path not working:
/usr/bin/R
```

using the docker image [rocker/r-ver:4.0.0](https://hub.docker.com/r/rocker/r-ver). 

### Desired
Ideally the debugger would look for R in the PATH and not just at a single location. 

### Workaround

```shell
ln -s /usr/local/bin/R /usr/bin/R
```

**Comment by ManuelHentschel** [comment]
The path to the R executable can be set in the vscode setting `rdebugger.rterm.linux` (or `...windows`, `...mac` depending on your os), so using `ln` should not be necessary, even if your R installation is not in `PATH`. Does this work for you?

**Comment by ManuelHentschel** [comment]
I added a small note that the path can be changed in the extension settings to the error-message `R path not working`.

@renkun-ken: I think the `PATH` is only used to locate R if no R path is supplied at all (for the current os). But since we supply the path `/usr/bin/R` in the default settings, this won't be the case very often.

Do you think it makes sense to remove the default path? I.e. does searching the path have a better chance of success than assuming the default location?

**Comment by renkun-ken** [comment]
@ManuelHentschel Yes, we should remove the default paths as did by https://github.com/Ikuyadeu/vscode-R/commit/3b59667e40fcbb624adbc7fe373eeeaf8e8a798f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 in vscode-R.

**Comment by FelixBenning** [comment]
I am not sure how if this works like a shebang, but maybe you could use `/usr/bin/env R` as a default? cf. [Stackexchange question](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my)

**Comment by renkun-ken** [comment]
We could leave the default value blank and say in the settings description that blank indicates detecting R path from `PATH` and Windows registry. `/usr/bin/env R` is a command rather than an executable path.

**Comment by ManuelHentschel** [comment]
I added a note that blank settings indicate that `PATH` is used and a check for an empty string (done after searching the PATH/registry).

This way the user should never see an empty path as error message but rather the (non-working) path or a message that no path was found at all.
